require "plugins"
require "opts"
require "binds"
require "plug-config.cmp"
require "plug-config.indent-blankline"
require "plug-config.lsp-signature"
require "plug-config.lualine"
require "plug-config.luasnip"
require "plug-config.mason"
require "plug-config.null-ls"
require "plug-config.nvim-metals"
require "plug-config.project"
require "plug-config.telescope"
require "plug-config.treesitter"
require "plug-config.quickscope"
require "plug-config.vimtex"
-- Include lsp last
require "lsp.lsp"
