require('binds')
require('plugins')
require('lsp')
require('plug-config.treesitter')
require('plug-config.cmp')
require('plug-config.lsp-signature')
require("plug-config.autopairs")
require("plug-config.quickscope")
require("plug-config.lualine")
require("plug-config.nvim-metals")
require('opts')
require('plug-config.nerdtree')
require('plug-config.indent-blankline')

